version: "2.1"

services:
  client:
    build: ../docker/ops-playground-image
    image: apache/flink-ops-playground:1-FLINK-1.10-scala_2.11
    # command: "flink run -d -p 2 /opt/apps/flink-playground-clickcountjob-1-FLINK-1.10_2.11.jar --bootstrap.servers kafka:9092 --checkpointing --event-time"
    command: /bin/bash
    stdin_open: true
    tty: true

    depends_on:
      - jobmanager
      - kafka
    volumes:
      - ./conf:/opt/flink/conf
      - ./apps:/opt/apps
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  clickevent-generator:
    image: apache/flink-ops-playground:1-FLINK-1.10-scala_2.11
    command: "java -classpath /opt/ClickCountJob.jar:/opt/flink/lib/* org.apache.flink.playgrounds.ops.clickcount.ClickEventGenerator --bootstrap.servers kafka:9092 --topic input"
    depends_on:
      - kafka

  jobmanager:
    image: flink:1.10-scala_2.11
    command: "jobmanager.sh start-foreground"
    ports:
      - 8081:8081
    volumes:
      - ./conf:/opt/flink/conf
      - flink-checkpoints-directory:/tmp/flink-checkpoints-directory
      - /tmp/flink-savepoints-directory:/tmp/flink-savepoints-directory
      - ./flink-metrics-prometheus_2.11-1.10.0.jar:/opt/flink/lib/flink-metrics-prometheus_2.11-1.10.0.jar
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    image: flink:1.10-scala_2.11
    depends_on:
      - jobmanager
    command: "taskmanager.sh start-foreground"
    ports:
      - 8789:8789
    volumes:
      - ./conf:/opt/flink/conf
      - flink-checkpoints-directory:/tmp/flink-checkpoints-directory
      - /tmp/flink-savepoints-directory:/tmp/flink-savepoints-directory
      - ./flink-metrics-prometheus_2.11-1.10.0.jar:/opt/flink/lib/flink-metrics-prometheus_2.11-1.10.0.jar
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "input:2:1, output:2:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9094:9094

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"

volumes:
  flink-checkpoints-directory:
